development:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: iqvoc_development
  pool: 5
  username: root
  password:
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: iqvoc_test
  pool: 5
  username: root
  password:
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: iqvoc_production
  pool: 15
  username: <%= ENV['DB_USER'] || "root" %>
  password: <%= ENV['DB_PW'] || "" %>
  host: <%= ENV['DB_HOST'] || "127.0.0.1" %>
